spring.application.name=Ministry-Records-Management-System
server.port=7006
spring.datasource.url=jdbc:postgresql://localhost/MinistryRecordsManagementSystem
spring.datasource.username=postgres
spring.datasource.password=root

